SELECT DATABASE()POKEDEX;

SHOW COLUMNS FROM POKEMON;

SELECT * FROM POKEMON;

SELECT NUMERO,
	   NOME,
	   COR,
	   ALTURA_M,
	   PESO_KG 
FROM POKEMON;

SELECT NUMERO,
	   NOME 
FROM POKEMON 
WHERE GERACAO = 1;

SELECT * FROM POKEMON 
WHERE GERACAO = 1 
AND COR = 'Amarelo';

SELECT NOME,
	   ATAQUE 
FROM POKEMON
ORDER BY ATAQUE DESC LIMIT 1;

SELECT NUMERO,
	   NOME,
	   TIPO1 
FROM POKEMON 
WHERE TIPO1 = 'fire';

SELECT NUMERO,
	   NOME,
	   DEFESA
FROM POKEMON
ORDER BY NUMERO DESC;

SELECT NUMERO,
	   NOME 
FROM POKEMON 
ORDER BY TAXA_CAPTURA LIMIT 1;

SELECT * FROM POKEMON 
WHERE TIPO2
IS NULL;

SELECT NUMERO,
	   NOME,
	   TIPO1,
	   TIPO2
FROM POKEMON
WHERE PESO_KG 
BETWEEN 100 AND 500;

SELECT NUMERO,
NOME,
VELOCIDADE
FROM POKEMON
ORDER BY  VELOCIDADE DESC LIMIT 10;

SELECT NUMERO,
	   NOME,
	   TIPO1,
	   TIPO2,
	   TAXA_CAPTURA
FROM POKEMON
WHERE TIPO1 IS NOT NULL
AND TIPO2 IS NOT NULL
AND TAXA_CAPTURA >100
ORDER BY TAXA_CAPTURA DESC;

SELECT DISTINCT TIPO1 FROM POKEMON;

SELECT NUMERO,
	   NOME,
	   COR 
FROM POKEMON
WHERE NOME LIKE '%d%';

SELECT NOME,
	   TOTAL 
FROM POKEMON
ORDER BY TOTAL DESC LIMIT 1;

SELECT NUMERO,
	   NOME,
	   DEFESA,
	   ATAQUE
FROM POKEMON
WHERE DEFESA>60
AND ATAQUE<=70
ORDER BY TOTAL DESC;

SELECT * FROM POKEMON
WHERE TIPO1='planta' 
OR TIPO1='venenoso'
AND TIPO2='planta'
OR TIPO2='venenoso'
AND COR != 'Green'
ORDER BY NOME ASC;

SELECT NOME FROM POKEMON 
WHERE NOME LIKE '%y%';

SELECT ATAQUE_ESPECIAL
FROM POKEMON
ORDER BY ATAQUE_ESPECIAL
DESC LIMIT 1;

SELECT NUMERO,
	   NOME,
	   ALTURA_M 
FROM POKEMON
WHERE ALTURA_M >2.10;

SELECT DISTINCT COR 
FROM POKEMON 
ORDER BY COR ASC;

SELECT NOME,
	   VELOCIDADE
FROM POKEMON
WHERE VELOCIDADE BETWEEN 30 AND 70 
ORDER BY NOME ASC,
VELOCIDADE DESC;

SELECT NOME,
       LENDARIO
FROM POKEMON 
WHERE LENDARIO=1
ORDER BY TOTAL DESC;

SELECT * FROM POKEMON
WHERE GERACAO=1 
AND TAXA_CAPTURA = 255;

SELECT NOME 
FROM POKEMON
WHERE NOME = 'pikachu'
OR NOME ='Squirtle'
OR NOME='Bulbasaur'
OR NOME= 'Charmander'
ORDER BY TOTAL DESC;

SELECT NOME
FROM POKEMON
WHERE NOME LIKE '%d%'
AND GERACAO=1
AND TIPO2
IS NOT NULL ORDER BY TAXA_CAPTURA ASC, 
TOTAL DESC;

SELECT NUMERO,
       NOME,
	   TOTAL,
	   TAXA_CAPTURA
FROM POKEMON
WHERE LENDARIO=1 
ORDER BY TAXA_CAPTURA ASC, TOTAL ASC;

SELECT NUMERO,
	   NOME,
	   PESO_KG 
FROM POKEMON
WHERE PESO_KG BETWEEN 2 AND 3; 

SELECT NUMERO,
       NOME,
	   TIPO1,
	   TIPO2
FROM POKEMON
WHERE TIPO1='normal'
AND TIPO2 IS NULL AND LENDARIO=0;

SELECT NUMERO,
       NOME,
	   TIPO1,
	   TIPO2,
	   COR 
FROM POKEMON
WHERE COR !='Blue' 
ORDER BY NOME ASC;

SELECT NOME,
       VELOCIDADE
FROM POKEMON
ORDER BY VELOCIDADE
ASC LIMIT 10;

SELECT NOME
FROM POKEMON
WHERE NOME LIKE '%a%';

SELECT NOME 
FROM POKEMON
WHERE TIPO1='fire' 
AND COR !='red' 
ORDER BY NOME ASC;

SELECT DISTINCT PESO_KG 
FROM POKEMON 
ORDER BY PESO_KG ASC;

SELECT NUMERO,
       NOME,
	   HP 
FROM POKEMON
WHERE HP 
BETWEEN 0 
AND 100 
ORDER BY HP,NOME ASC;

SELECT NUMERO,
       NOME,
	   HP,
	   ATAQUE,
	   DEFESA,
	   TOTAL 
FROM POKEMON
WHERE HP >=100
AND ATAQUE>=100
AND DEFESA>=100; 

SELECT NOME,
       TIPO1
FROM POKEMON
WHERE TIPO1='Water'
OR TIPO1='gelo'
ORDER BY TOTAL DESC;